blog/urls.py
from django.urls import path
from .views import *
from .import views

app_name = "blog"


urlpatterns = [
    path('', views.posts_list, name="posts_list_url"),
    path('post/<str:slug>/', PostDetail.as_view(), name="post_detail_url"),
    path('tags/', views.tags_list, name="tags_list_url"),
    path('tag/create', TagCreate.as_view(), name="tag_create_url"),
    path('taga/<str:slug2>/',  TagDetail.as_view(), name="tags_detail_url"),

]

blogengine/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.shortcuts import reverse


class Post(models.Model):
    title = models.CharField(max_length=150, db_index=True)
    slug = models.SlugField(max_length=150, unique=True)
    body = models.TextField(blank=True, db_index=True)
    tags = models.ManyToManyField('Tag', blank=True, related_name='posts')
    date_pub = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("post_detail_url", kwargs={'slug': self.slug})




    def __str__(self):
        return self.title



class Tag(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True)


    def __str__(self):
        return "{}" .format(self.title)

blog/forms.py
from django import forms
from .models import Tag
from django.core.exceptions import ValidationError


class TagForm(forms.Form):
    title  = forms.CharField(max_length=50)
    slug = forms.CharField(max_length=50)

    title.widget.attrs.update({'class': 'form-control'})
    slug.widget.attrs.update({'class': 'form-control'})

    def clean_slug(self):
        new_slug = self.cleaned_data['slug'].lower()

        if new_slug == 'create':
            raise ValidationError('Slug may not be "Create"')
        if Tag.objects.filter(slug__iexact=new_slug).count():
            raise ValidationError('Slug must be unique. We have "{}" slug already'.format(new_slug))
        return new_slug

    def save(self):
        new_tag = Tag.objects.create(
            title=self.cleaned_data['title'],
            slug=self.cleaned_data['slug']

        )
        return new_tag

blog/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.views.generic import View
from .models import Post, Tag
from .utils import  ObjectDetailMixin
from .forms import TagForm

def posts_list(request):
    posts = Post.objects.all()
    return render(request, 'blog/index.html', context={'posts':posts})


#def post_detail(request, slug2):
    #post = Post.objects.get(slug__iexact=slug2)

    #return render(request, 'blog/post_detail.html', context={'post':post})


class PostDetail( View):
    def get(self, request, slug):
        #post = Post.objects.get(slug__iexact=slug)
        post = get_object_or_404(Post, slug__iexact=slug)
        return render(request, 'blog/post_detail.html', context={'post':post})

def tags_list(request):
    tags = Tag.objects.all()
    return render(request, 'blog/tags_list.html', context={'tags':tags})



#def tags_detail(request, slug2):
    #tag = Tag.objects.get(slug__iexact=slug2)
    #return render(request, 'blog/tags_detail.html', context={'tag':tag})


class TagDetail( View):
    def get(self, request, slug2):
        #tag = Tag.objects.get(slug__iexact=slug2)
        tag = get_object_or_404(Tag, slug__iexact=slug2)
        return render(request, 'blog/tags_detail.html', context={'tag':tag})




class TagCreate(View):
    def get(self, request):
        form = TagForm()
        return render(request, 'blog/tag_create.html', context={'form':form})

    def post(self, request):
        bound_form = TagForm(request.POST)

        if bound_form.is_valid():
            new_tag = bound_form.save()
            return redirect(new_tag)
        return render(request, 'blog/tag_create.html', context={'form':bound_form})

blogengine/views.py
from django.http import HttpResponse


def home(request):
    return HttpResponse('<h1>Hello world</h1>')

blog/templates/blog/base_blog.html
{% extends 'base.html' %}

blog/templates/blog/includes/post_card_template.html
<div class="card mb-4">
  <div class="card-header">
    <h2>{{ post.title }}</h2>
  </div>
  <div class="card-body">
    <h5 class="card-title"><p>{{ post.body }}</p></h5>
    <p class="card-text"><em>{{ post.date_pub }}</em></p>
    <a href="{% url 'blog:post_detail_url' slug=post.slug %}" class="btn btn-primary">Read</a>
  </div>
</div>

blog/templates/blog/index.html
{% extends 'blog/base_blog.html' %}
    <h2>i hate extends</h2>


{% block title %}
  Posts list
{% endblock %}


{% block content %}
  {% for post in posts %}

  {% include 'blog/includes/post_card_template.html' %}

  {% endfor %}
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base_blog.html' %}

{% block title %}
  {{ post.title }} - {{ block.super }}
{% endblock %}


{%  block content %}
  <h1 class="mt-5">
    {{ post.list }}
  </h1>
  <p>
    {{ post.body }}
  </p>

{% endblock %}

blog/templates/blog/tag_create.html
{% extends 'blog/base_blog.html' %}

{% block title %}
  Tag Create - {{ block.super }}
{% endblock %}


{% block content %}
  <form class="" action="{% url 'blog:tag_create_url' %}" method="post">
    {% csrf_token %}
      {% for field in form %}
        <div class="form-group">
          {% if field.errors %}
            <div class=".alert.alert-danger">
              {{ field.errors }}
            </div>
          {% endif %}

          {{ field.label }}
          {{ field }}


        </div>

      {% endfor %}


    <button type="submit" class="btn btn-primary">Create Tag</button>
  </form>
{% endblock %}

blog/templates/blog/tags_detail.html
{% extends 'blog/base_blog.html' %}

{% block title %}
  {{ tag.title }} - {{ block.super }}
{% endblock %}


{%  block content %}
  <h1 class="mt-5">Post with  "{{ tag.title|title }}" tag:</h1>
  {% for post in tag.posts.all %}
  <div class="card mb-4">
    <div class="card-header">
      <h2>{{ post.title }}</h2>
    </div>
    <div class="card-body">
      <h5 class="card-title"><p>{{ post.body }}</p></h5>
      <p class="card-text"><em>{{ post.date_pub }}</em></p>
      <a href="{% url 'blog:post_detail_url' slug=post.slug %}" class="btn btn-primary">Read</a>
    </div>
  </div>
  {% endfor %}

{% endblock %}

blog/templates/blog/tags_list.html
{% extends 'blog/base_blog.html' %}

{% block title %}
  Tags list - {{ block.super }}
{% endblock %}



{% block content %}
  <h1 class="mb-5">Tags:</h1>
  {% for tag in tags %}
    <h3><a href="{% url 'blog:tags_detail_url' slug2=tag.slug %}" >{{ tag.title }}</a></h3>
  {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>
      {% block title %}
        Blog Engine
      {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:posts_list_url' %}">Posts<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:tags_list_url' %}">Tags</a>
      </li>

      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

<div class="container">
    <div class="row">
          <div class="col-6 offset-md-2">
            {% block content %}
              There fucked-up content
            {% endblock %}

          </div>
    </div>
</div>
  </body>
</html>